# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Evaluate.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(630, 500)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(160, 25, 321, 21))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.selecteam_cb = QtWidgets.QComboBox(Dialog)
        self.selecteam_cb.setGeometry(QtCore.QRect(85, 75, 130, 25))
        self.selecteam_cb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.selecteam_cb.setObjectName("selecteam_cb")
        self.selectmatch_cb = QtWidgets.QComboBox(Dialog)
        self.selectmatch_cb.setGeometry(QtCore.QRect(395, 75, 131, 25))
        self.selectmatch_cb.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.selectmatch_cb.setObjectName("selectmatch_cb")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(40, 120, 551, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.calscore_btn = QtWidgets.QPushButton(Dialog)
        self.calscore_btn.setGeometry(QtCore.QRect(240, 415, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.calscore_btn.setFont(font)
        self.calscore_btn.setObjectName("calscore_btn")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(80, 160, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(340, 160, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.Points_lw = QtWidgets.QListWidget(Dialog)
        self.Points_lw.setGeometry(QtCore.QRect(345, 180, 191, 221))
        self.Points_lw.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Points_lw.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.Points_lw.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.Points_lw.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.Points_lw.setObjectName("Points_lw")
        self.Players_lw = QtWidgets.QListWidget(Dialog)
        self.Players_lw.setGeometry(QtCore.QRect(80, 181, 191, 221))
        self.Players_lw.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Players_lw.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.Players_lw.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.Players_lw.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.Players_lw.setObjectName("Players_lw")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Evaluate the score of your team"))
        self.calscore_btn.setText(_translate("Dialog", "Calculate Score"))
        self.label_2.setText(_translate("Dialog", "Players"))
        self.label_3.setText(_translate("Dialog", "Points"))
        self.calscore_btn.setShortcut(_translate("Dialog","Return"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
