# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'New_Team.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(386, 337)
        self.Team_name = QtWidgets.QLineEdit(Dialog)
        self.Team_name.setGeometry(QtCore.QRect(70, 140, 241, 51))
        self.Team_name.setAlignment(QtCore.Qt.AlignCenter)
        self.Team_name.setObjectName("Team_name")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(80, 60, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.save_name = QtWidgets.QPushButton(Dialog)
        self.save_name.setGeometry(QtCore.QRect(150, 230, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.save_name.setFont(font)
        self.save_name.setObjectName("save_name")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Team_name.setPlaceholderText(_translate("Dialog", "Enter Team Name"))
        self.label.setText(_translate("Dialog", "Create New Team"))
        self.save_name.setText(_translate("Dialog", "Save"))
        self.save_name.setShortcut(_translate("Dialog","Return"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
